### ISSUE TITLE
script.js cannot be loaded when Razor component is emended in an Razor page [Blazor Server]

### ISSUE THREAD

**Issue by wolfgangschneider** [Append-IT/Blazor.Printing#1]
Hi

the Blazor.Print works well in an pure Blazor App.  I am  adding Blazor to an existing  MVC / Rzor pages Project. When calling  PrintingService.Print in an Razor component and t5his razor component is embedder in an razor Page the script.js could not be doinloaded  to the server. 

* On a pure Blazor project  the  ImportModule()  function try to download the script.js file from _content/Append.Blazor.Printing/scripts.js

* if the Razor component is embedded the  ImportModule()  function try to download the script.js file from **XXXXRazorPage**_content/Append.Blazor.Printing/scripts.js

**Comment by wolfgangschneider** [comment]
// this could help  
internal async ValueTask ImportModule()
        {
           // module = await jsRuntime.InvokeAsync<IJSObjectReference>("import", "./_content/Append.Blazor.Printing/scripts.js");
            module = await jsRuntime.InvokeAsync<IJSObjectReference>("import", $"{this.navigationManager.BaseUri}_content/Append.Blazor.Printing/scripts.js");

        }

**Comment by vertonghenb** [comment]
@wolfgangschneider Interesting, is there some general guidance on this in the Blazor Docs? Because this might cause problems elsewehere. If you like PR's are welcome, don't forget to create a MVC example so we can test it later on.

**Comment by DrTekno** [comment]
Hi,

Is this error related to this problem?

![image](https://user-images.githubusercontent.com/33718346/129341790-be9f8df6-839a-4d51-a8ed-e4087f5480bc.png)

Im not in a pure Blazor App indeed.

Thanks
