### ISSUE TITLE
Passing headers

### ISSUE THREAD

**Issue by americanslon** [Append-IT/Blazor.Printing#10]
I can't seem to find see a way to pass headers to the internal HttpClient. Is there a way?
It's useful if the URL of that serves the PDF requires an authorization header (as any decent API should).

Thanks!

**Comment by vertonghenb** [comment]
@americanslon We're using PrintJS as a baseline and this function is currently not implemented yet. However as described by Crabby himself you can first fetch the pdf contents using any HTTPClient you want with the headers attached and then send it to the printservice as a base64. 

https://github.com/crabbly/Print.js/issues/402
