### ISSUE TITLE
When printing with PrintType.html, css is not applied.

### ISSUE THREAD

**Issue by hellowkc12** [Append-IT/Blazor.Printing#11]
@onclick="@(_ => PrintingService.Print("printable-form", PrintType.Html))"

```
<form id="printable-form">
    html code..
</form>
```

I want to print this picture.
![Screenshot_1](https://user-images.githubusercontent.com/24710971/180914456-12ed5941-a63b-42c8-b5e8-b2655e0048a0.png)

However, when printed, it comes out like this:
![image](https://user-images.githubusercontent.com/24710971/180916664-7a57e355-57cf-41d5-becc-78b859c84c7b.png)

**Comment by vertonghenb** [comment]
@Luk164 can you give me a repo that I can reproduce this issue with?

**Comment by Luk164** [comment]
@vertonghenb I can do you one better, check out the PR I made https://github.com/Append-IT/Blazor.Printing/pull/16. It also has the link to original issue with PrintJS and all the explanations.

**Comment by coeur85** [comment]
any words on this ?

**Comment by Luk164** [comment]
> any words on this ?

I think the lib is dead, if you need it make a fork yourself and merge my PR into it, though I would suggest looking for an alternative

**Comment by vertonghenb** [comment]
> > any words on this ?
> 
> I think the lib is dead, if you need it make a fork yourself and merge my PR into it, though I would suggest looking for an alternative

Totally forgot about this! Thanks for the reminder! I'll check the PR ASAP.
