### ISSUE TITLE
Error when printing in Kiosk mode

### ISSUE THREAD

**Issue by gle4711** [Append-IT/Blazor.Printing#12]
I want to print from the browser immediately without a print dialog. To do this, you can start the browser in kiosk mode. For example:
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" http://localhost:5000 --kiosk-printing

When you run it, an error will be displayed immediately.I want to print from the browser immediately without a print dialog. To do this, you can start the browser in kiosk mode. For example:
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" http://localhost:5000 --kiosk-printing

When you run it, an error will be displayed immediately

https://user-images.githubusercontent.com/62564122/182022181-d574f455-b7ad-4b0f-87f0-7709016a2d4a.mp4

.

**Comment by vertonghenb** [comment]
Hi @gle4711 
Have you allowed printing mode when running via --kiosk? 
The docs are for Edge but it uses Chromium so I think it's gonna be something like this:
https://learn.microsoft.com/en-us/deployedge/microsoft-edge-configure-kiosk-mode
and specifically the PritingMode: https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#printingenabled

Can you check and paste an English version of the error in the issue?
