### ISSUE TITLE
Is there a way to bypass the dialog?

### ISSUE THREAD

**Issue by knight1219** [Append-IT/Blazor.Printing#17]
Hi there! I've been looking at your library and it seems to do almost everything I need for a project I am working on. We have a new requirement where we need to bypass the dialog and set things like printer name, copies, ect in code. I didn't see any of these properties exposed but wanted to ask and see if this was something available.

If these properties aren't available in the Blazor side of things, does PrintJs allow this?

**Comment by genesila** [comment]
The same requirement for me. Is there something like `PrintingService.Print(".../x_large_printjs.pdf", directPrint:true)` option?

**Comment by Aculeo** [comment]
Doesn't appear to be possible with conventional means, for security reasons (so websites can't just print stuff without user confirmation). 

This SO topic covers some solutions:
https://stackoverflow.com/questions/9213660/html-javascript-one-click-print-no-dialogs

**Comment by vertonghenb** [comment]
As @Aculeo mentioned this is not possible due to the sandbox environment we're running in.
