### ISSUE TITLE
Printing doesn't work on Firefox

### ISSUE THREAD

**Issue by Aculeo** [Append-IT/Blazor.Printing#19]
I've been getting blank pages when printing with Firefox (111). I also tested it with Chromium, and it works fine there.

![grafik](https://user-images.githubusercontent.com/3977620/229306486-a9f1caff-0dea-47b5-a858-42153337848f.png)

This appears to be a recent issue, something caused by Firefox itself, because when I originally tested it, it worked. And downgrading the library to an older version didn't help either.

**Comment by vertonghenb** [comment]
@Aculeo this issue is being solved in the javascript version. 
https://github.com/crabbly/Print.js/issues/665
We're waiting for an official release of the fix, once it's there we'll update our version.

**Comment by Aculeo** [comment]
I'm not how patient we have to be for an official fix, print.js seems abandoned? Last release is from 2021.

In the issue you linked there was a fork mentioned, which I've tried out, and it does indeed solve the problem. I simply replaced the print.js code in the library with this: https://www.npmjs.com/package/print-js-updated?activeTab=code and now printing in Firefox works.

**Comment by vertonghenb** [comment]
Fixed in 6.3.0 also works in Safari now.
@Aculeo Thanks for the fix!
