### ISSUE TITLE
Blazor server Example

### ISSUE THREAD

**Issue by keter83** [Append-IT/Blazor.Printing#2]
Hi,  Your Software it's a like a piece of gold!  really needed that.  Unfortunately  I am a beginner with blazor and I cannot understand how to use is with Blazor Server. ( the example is for WASM but there are differences )  would be possible for you to put an example for Blazor Server ?
thank you so much.

**Comment by vertonghenb** [comment]
@keter83 Example was added and can be seen in the /samples folder. However you can also refer to [this commit](https://github.com/Append-IT/Blazor.Printing/commit/b1056efbc06a304be93f30684bd8cdef34adf42a) to see what was needed to add PrintingService to the Server Application.
