### ISSUE TITLE
Firefox not working

### ISSUE THREAD

**Issue by franklupo** [Append-IT/Blazor.Printing#24]
The sample in Firefox not working

![image](https://github.com/Append-IT/Blazor.Printing/assets/6276309/394ea498-afa4-4b51-a7f6-83dea4fad0be)

![image](https://github.com/Append-IT/Blazor.Printing/assets/6276309/4da3716c-98b1-4ca0-ac71-f38ada83b5ac)

**Comment by vertonghenb** [comment]
Fixed in 6.3.0
