### ISSUE TITLE
Using @media print css

### ISSUE THREAD

**Issue by chemala** [Append-IT/Blazor.Printing#26]
I am currently using the service to print an image element. The problem is, I need to scale the element up when printing. I tried using `@media print` and then scale the element there, but it seems the query does not work with this service. Is there a workaround?

**Comment by vertonghenb** [comment]
An alternative and possibly a better workaround since, printing HTML from the page is quite inconsistent in the base library. But you can, generate the PDF using [Quest.PDF ](https://www.questpdf.com), and use this service to get the Print Dialog to print the file.
