### ISSUE TITLE
Is it possible to print a local file?

### ISSUE THREAD

**Issue by paulocarinhena** [Append-IT/Blazor.Printing#27]
Is it possible to print a local PDF file?

example:
string LocalFileName = "C:\Users\work\AppData\Local\Temp\fileExample.pdf";

PrintingService.Print(LocalFileName, showModal: true);

I tried, but without success.

**Comment by vertonghenb** [comment]
That won't be possible, however:
Read the file using an[`<InputFile/>`](https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-8.0)  Component and convert it to a BASE64 then print it.
