### ISSUE TITLE
Print PDF outside the wwwroot folder

### ISSUE THREAD

**Issue by aurquiel** [Append-IT/Blazor.Printing#28]
Hello

Is there a way to print a pdf file outside the wwwroot folder? I pass the location,different form wwwroot ,but it prefixes wwwroot in the path and give me error.

Thanks

**Comment by aurquiel** [comment]
I am telling this because wwwroot folder is not writeable so you only can print documents that already exist you cant create docuemnts and printing them

**Comment by vertonghenb** [comment]
@aurquiel It does not matter to the library where the file is located. If you create a Controller and return a FileResult, you can put the file wherever you'd like. From the lib, you can call the endpoint. 

For example:
```razor
        <button type="button" @onclick="@(() => PrintingService.Print("https://printjs.crabbly.com/docs/large_printjs.pdf", showModal:true))">
            Print Large PDF ( 5mb file )
        </button>
```
