### ISSUE TITLE
print without pdf file and show print dialog

### ISSUE THREAD

**Issue by tahafathi2013** [Append-IT/Blazor.Printing#29]
hi
I have a report that is set as a code and it is a very simple report. When the client clicks on the button, I want the information to go from the controller to the report and be printed without a preview. I use Page Razor, not Blazor. Thank you for your help. How can I do this?

![code](https://github.com/user-attachments/assets/b7a6d242-3d95-4afe-9bc4-e7630a105a97)

![rp](https://github.com/user-attachments/assets/03a2af82-c017-4db6-9e93-35630a567ae4)

**Comment by vertonghenb** [comment]
@tahafathi2013 Not really sure what you need here, can you explain what's the problem with the library?

**Comment by vertonghenb** [comment]
Directly printing cannot be done in the Browser due to the JS sandbox. However an alternative has been provided in the base lib.
https://github.com/crabbly/Print.js/issues/517
