### ISSUE TITLE
using Append.Blazor.Printing not available

### ISSUE THREAD

**Issue by nelsonbatista** [Append-IT/Blazor.Printing#3]
Hello,

I've added Install-Package Append.Blazor.Printing to my project. when I try to added to my project by adding "using Append.Blazor.Printing" it does not work.
I can't inject IPrintingService in my program.

My project is a Blazor WASM.

Best regards

**Comment by vertonghenb** [comment]
Which .NET version are you using? It's compatible with 5.0 and greater.

**Comment by nelsonbatista** [comment]
Hello,

I'm still using version 3.1.

Best regards

**Comment by vertonghenb** [comment]
The package is only supported for 5.0 and greater. I advise you to update your 3.1 to 5.0.
