### ISSUE TITLE
Printing of PDF not working in Edge Version 126.0.2592.113

### ISSUE THREAD

**Issue by phomberger** [Append-IT/Blazor.Printing#30]
Hi,
downloaded the GIT repo and running the Append.Blazor.Printing.Documentation project. With Chrome and Firefox all examples are working very good. When I open the example page with Edge Version 126.0.2592.113, only HTML and Raw HTML is working. All other examples like the base64 printing only opens the print dialog, but then after commiting print on a device from the list, nothing is happening. Also no error messages in the developer tools are shown. Can you please help?

**Comment by vertonghenb** [comment]
@phomberger I don't think this is related to the library itself, but could be related to the print driver? Does "Save as PDF"  work if this is the case it's a device problem.
