### ISSUE TITLE
The type or namespace name 'Append' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by mackecar** [Append-IT/Blazor.Printing#4]
Hi,
After I installed nuget package there I got this error:

![image](https://user-images.githubusercontent.com/5793984/106618396-b48f5680-656f-11eb-8a7b-e3fdecfea3fb.png)

**Comment by vertonghenb** [comment]
@mackecar thanks for raising this issue!
I think you're using dotnet 3.x and not 5.0 which is a precondition to use this library.
Can you send a repo or a screenshot of your .csproj to be sure?

**Comment by mackecar** [comment]
> 
> 
> @mackecar thanks for raising this issue!
> I think you're using dotnet 3.x and not 5.0 which is a prerequisite to use this library.
> Can you send a repo or a screenshot of your .csproj to be sure?

Yes, you are totally right. I didn't change from dot net core 3 to dot net 5.
Thank you for the help.
