### ISSUE TITLE
Mobile browser 

### ISSUE THREAD

**Issue by ekjuanrejon** [Append-IT/Blazor.Printing#7]
Does not seem to work in mobile browser..
.

**Comment by vertonghenb** [comment]
Which Browser are you using? I can confirm it works on Safari iOS

**Comment by AJDonwieboy** [comment]
I have the same issue, while using Chrome-Debugger -> Mobile-View

**Comment by vertonghenb** [comment]
This is a problem in the base library and unfortunately cannot be resolved in this package. Once it's resolved we'll merge it in here.
https://github.com/crabbly/Print.js/issues/33
