### ISSUE TITLE
it's not printing. instead downloading the file

### ISSUE THREAD

**Issue by hintsofttech** [Append-IT/Blazor.Printing#9]
i have tried this nuget.
it's not printing. instead downloading the file.
please check and suggest.

**Comment by vertonghenb** [comment]
We do need some more information about your case:
- Blazor WASM or Blazor Server
- Browser + version
- Operating system
- .NET version

**Comment by hintsofttech** [comment]
@vertonghenb sir,
still waiting for your support.

**Comment by hintsofttech** [comment]
@vertonghenb  no reply sir...

**Comment by vertonghenb** [comment]
@hintsofttech Do know this a free open-source package and you're always welcome to create a PR.

However I cannot reproduce the issue you're describing can you try to use it on this website and see if it prints? 
https://blazor-printing.append.be

If the issue persists, it could be a local Chrome problem. You can try the steps provided in this issue:
https://appuals.com/fix-cant-print-from-google-chrome/

**Comment by hintsofttech** [comment]
Dear Sir,
yours is working even in my laptop's chrome very well and directly going to printing.

please check my code below:
[Downloading Instead of Printing](https://github.com/hintsofttech/-Append.Blazor.Printing-Downloading-The-File-Insteadhttps-github.com-new-of-Printing-In-.Net7-Blaz)

which is not working.
kindly suggest...

**Comment by vertonghenb** [comment]
@hintsofttech This does not seem to be an issue in the library but something with your Chrome/Edge Settings. As mentioned before check this link: https://appuals.com/fix-cant-print-from-google-chrome/

![image](https://user-images.githubusercontent.com/10981553/175020619-50bfde8c-48b5-41c7-a891-9313d982e944.png)

**Comment by hintsofttech** [comment]
sir, from your above provided link, 
it's printing from my all the browsers
that means no problem is with browser.

kindly please check my project it's downloading.
is any problem with that project and any mistake i am making there ?
